Repository QuadNard/devscoreboard, pull requests merged in 2023-10, with the labels that each got.

#6 Framer Motion Title Screen
  README.md
  package-lock.json
  package.json
  postcss.config.js
  public/imgs/Witch.jpg
  src/App.css
  src/App.jsx
  src/components/layout/Layout.jsx
  src/components/layout/Loader.jsx
  src/components/ui/NotificationMenu.jsx
  src/components/ui/TitleScreenOverlay.jsx
  src/hooks/api.js
  src/index.css
  src/main.jsx
  src/pages/Quiz.jsx
  src/utils/parseSeconds.js
  tailwind.config.js
Labels: enhancement

#9 Integrated realtime firebase database
  env-example.md
  src/services/db.js
Labels: enhancement

#10 ✔ created modal component
  .eslintrc.cjs
  README.md
  package-lock.json
  package.json
  postcss.config.js
  src/App.jsx
  src/components/layout/Layout.jsx
  src/components/layout/Loader.jsx
  src/components/ui/Modal.jsx
  src/components/ui/NotificationMenu.jsx
  src/components/ui/TitleScreenOverlay.jsx
  src/index.css
  src/main.jsx
  src/pages/Quiz.jsx
  src/utils/cn.js
  src/utils/contants.js
  src/utils/parseSeconds.js
  tailwind.config.js
  vite.config.js
Labels: enhancement

#19 📜created state logic & mapped out data formatting
  .gitignore
  package-lock.json
  package.json
  src/App.jsx
  src/components/ui/Header.jsx
  src/components/ui/TitleScreenOverlay.jsx
  src/pages/Quiz.jsx
  src/pages/QuizSession.jsx
  src/services/Fakedata.js
  src/services/db/Firebase.js
  src/services/providers/QueryProvider.jsx
  src/services/state/Store.js
  src/utils/contants.js
Labels: enhancement, more advanced, API Integration

#22 ⚒ set webhooks from db
  src/components/ui/Header.jsx
  src/hooks/api.js
  src/hooks/useBlitzQuiz.js
  src/pages/QuizSession.jsx
  src/services/Fakedata.js
  src/services/db/Firebase.js
Labels: more advanced, API Integration

#23 Developed algorithm for random question selection
  src/pages/QuizSession.jsx
  src/utils/getRandomQuestions.js
Labels: documentation, enhancement

#25 Developed quiz question countdown
  src/components/ui/Modal.jsx
Labels: enhancement
